# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('zhinan', models.CharField(max_length=100)),
                ('search', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('must_credential', models.ManyToManyField(to='dc_app.Credential')),
            ],
        ),
        migrations.AddField(
            model_name='advice',
            name='advise_credential',
            field=models.ManyToManyField(to='dc_app.Credential'),
        ),
    ]
