# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='advise_credential',
        ),
        migrations.AddField(
            model_name='major',
            name='advise_credential',
            field=models.ManyToManyField(related_name='advise_c', to='dc_app.Credential'),
        ),
        migrations.AlterField(
            model_name='major',
            name='must_credential',
            field=models.ManyToManyField(related_name='must_c', to='dc_app.Credential'),
        ),
        migrations.DeleteModel(
            name='Advice',
        ),
    ]
